import type { TutorialDefinition } from '@/types/network';

export const tutorials: TutorialDefinition[] = [
    {
        id: 'getting-started',
        title: 'Getting Started',
        summary: 'Add devices, connect them, and run the simulation.',
        steps: [
            {
                id: 'add-device',
                title: 'Add two PCs',
                body: 'Drag two PCs from the sidebar onto the canvas (PC1 and PC2).',
                target: 'sidebar',
                completeOnEventType: undefined,
            },
            {
                id: 'connect-devices',
                title: 'Cable them together',
                body: 'Select the Connect tool (press C) and click PC1 then PC2 to draw a cable between them.',
                target: 'canvas',
                completeOnEventType: 'link',
            },
            {
                id: 'start-sim',
                title: 'Start simulation',
                body: 'Press Start in Simulation controls so links and ARP run.',
                target: 'sidebar',
                completeOnEventType: 'system',
            },
            {
                id: 'open-terminal',
                title: 'Open PC1 terminal',
                body: 'Double-click PC1 to open its terminal and leave it open.',
                target: 'canvas',
                completeOnEventType: undefined,
            },
            {
                id: 'configure-ips',
                title: 'Give both PCs IPs',
                body: 'In PC1 terminal run: `ifconfig eth0 10.0.0.1 255.255.255.0`. Then open PC2 terminal and run: `ifconfig eth0 10.0.0.2 255.255.255.0`. Both must be in the same /24.',
                target: 'terminal',
                completeOnEventType: undefined,
            },
            {
                id: 'send-ping',
                title: 'Ping across the link',
                body: 'Back in PC1 terminal run: `ping 10.0.0.2`. You should see replies.',
                target: 'terminal',
                completeOnEventType: 'icmp',
            },
        ],
    },
    {
        id: 'dhcp-basics',
        title: 'DHCP Basics',
        summary: 'Serve IPs from a router and verify a client lease.',
        steps: [
            {
                id: 'add-router-pc',
                title: 'Add a router and a PC',
                body: 'Drag one Router and one PC onto the canvas.',
                target: 'sidebar',
                completeOnEventType: undefined,
            },
            {
                id: 'connect-router-pc',
                title: 'Cable them together',
                body: 'Use the Connect tool (C) and click Router then PC to link them.',
                target: 'canvas',
                completeOnEventType: 'link',
            },
            {
                id: 'start-sim-dhcp',
                title: 'Start simulation',
                body: 'Press Start in Simulation controls so links are active.',
                target: 'sidebar',
                completeOnEventType: 'system',
            },
            {
                id: 'configure-dhcp-server',
                title: 'Enable DHCP on the router',
                body: 'Open the router terminal and run: `dhcp server enable` then `dhcp pool 10.0.0.100 10.0.0.150` and `dhcp gateway 10.0.0.1`. Give the router interface an IP: `ifconfig eth0 10.0.0.1 255.255.255.0`.',
                target: 'terminal',
                completeOnEventType: undefined,
            },
            {
                id: 'dhcp-client',
                title: 'Request an IP on the PC',
                body: 'Open the PC terminal and run: `dhclient eth0`. Confirm with `ip addr` that it received an address in 10.0.0.x.',
                target: 'terminal',
                completeOnEventType: undefined,
            },
            {
                id: 'dhcp-ping',
                title: 'Ping the router',
                body: 'From the PC, run `ping 10.0.0.1` and check for replies.',
                target: 'terminal',
                completeOnEventType: 'icmp',
            },
        ],
    },
    {
        id: 'vlan-segmentation',
        title: 'VLAN Segmentation',
        summary: 'Place two PCs in different VLANs on a switch.',
        steps: [
            {
                id: 'add-switch-pcs',
                title: 'Add a switch and two PCs',
                body: 'Drag one Switch and two PCs onto the canvas.',
                target: 'sidebar',
                completeOnEventType: undefined,
            },
            {
                id: 'connect-pcs',
                title: 'Cable each PC to the switch',
                body: 'Use the Connect tool (C) to link each PC to the switch.',
                target: 'canvas',
                completeOnEventType: 'link',
            },
            {
                id: 'start-sim-vlan',
                title: 'Start simulation',
                body: 'Press Start so switch forwarding is active.',
                target: 'sidebar',
                completeOnEventType: 'system',
            },
            {
                id: 'assign-vlans',
                title: 'Assign access VLANs',
                body: 'Open the switch terminal. Run `vlan 10` and `vlan 20`. Enter interface configs: select the port for PC1 with `interface <pc1-port>` then `switchport mode access` and `switchport access vlan 10`. Do the same for PC2 port with VLAN 20.',
                target: 'terminal',
                completeOnEventType: undefined,
            },
            {
                id: 'set-pc-ips',
                title: 'Set PC IPs in their VLANs',
                body: 'On PC1 run `ifconfig eth0 10.0.10.2 255.255.255.0`. On PC2 run `ifconfig eth0 10.0.20.2 255.255.255.0`.',
                target: 'terminal',
                completeOnEventType: undefined,
            },
            {
                id: 'vlan-ping-fail',
                title: 'Verify isolation',
                body: 'Try `ping 10.0.20.2` from PC1. It should time out because they are in different VLANs.',
                target: 'terminal',
                completeOnEventType: undefined,
            },
        ],
    },
];
